### ISSUE TITLE
Graceful failure for invalid api_key

### ISSUE THREAD

**Issue by sloganking** [zahidkhawaja/rusty#3]
I don't currently have a valid OpenAI API key. But when attempting to run rusty with an invalid one, I get 

```
Error: Error("missing field `choices`", line: 8, column: 1)
```

That error is talking about an error in a file other than `main.rs`, yet without telling us witch one. So I don't think it's very useful. We should probably display something more understandable.

The problem seems to be coming from

```rust
let json: OpenAIResponse = serde_json::from_reader(body.reader())?
```

**Comment by zahidkhawaja** [comment]
Hey @sloganking! Just pushed an update to improve the error message. Thanks for your feedback!
